class AdminPage:
    CATALOG_MENU_BUTTON = '#menu-catalog > a'
    PRODUCTS_MENU_BUTTON = '#collapse1 > li:nth-child(2)'
    ADD_PRODUCT = '.page-header .pull-right .btn-primary'
    REMOVE_PRODUCT = '.page-header .pull-right .btn-danger'
    PRODUCT_NAME = '#input-name1'
    PRODUCT_META = '#input-meta-title1'
    PRODUCT_MODEL = '#input-model'
    DATA_TAB = '.nav-tabs >li:nth-child(2)'
    SAVE_PRODUCT = '.pull-right > .btn:nth-child(1)'
    PRODUCT_ROWS_IN_TABLE = 'tbody tr'
    PRODUCT_NAMES_IN_TABLE = PRODUCT_ROWS_IN_TABLE + ' td:nth-child(3)'
    PRODUCT_CHECKBOXES_IN_TABLE = PRODUCT_ROWS_IN_TABLE + ' td:nth-child(1)'
    EDIT_BUTTONS_IN_TABLE = PRODUCT_ROWS_IN_TABLE + ' td:nth-child(8)'
    ALERT = '.alert'
    SUCCESS_EDIT_ALERT_TEXT = 'Success: You have modified products!'
