class AdminPage:
    CATALOG_MENU_BUTTON = '#menu-catalog > a'
    PRODUCTS_MENU_BUTTON = '#collapse1 > li:nth-child(2)'
    ADD_NEW_PRODUCT = '.page-header .pull-right .btn-primary'
    PRODUCT_ROW = '.table > tbody tr'
    NEW_PRODUCT_NAME = '#input-name1'
    NEW_PRODUCT_META = '#input-meta-title1'
    DATA_TAB = '.nav-tabs >li:nth-child(2)'
    NEW_PRODUCT_MODEL = '#input-model'
    SAVE_NEW_PRODUCT = '.pull-right > .btn:nth-child(1)'
